name: API Tests

on:
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: screener
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn[standard] sqlmodel psycopg2-binary python-dotenv pytest httpx
    
    - name: Run tests
      run: |
        cd api
        python -m pytest tests/ -v
      env:
        DATABASE_URL: postgresql://postgres:devpass@localhost:5432/screener 